apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: {{ .Values.namespaces.virtualservice }}
spec:
  hosts:
    - {{ .Values.host | quote }}
  gateways:
    {{ range .Values.gateways }}
    - {{ . | quote }}
    {{ end }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.prefix | quote }}
      route:
        - destination:
            host: {{ .Values.destination.host | quote }}
            port:
              number: {{ .Values.destination.port }}
