apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: {{ .Values.namespaces.gateway }}
  labels:
    {{- include "helm-cve-certificate.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingress # use the default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.host }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: grafana-nexflare-tls
      hosts:
        - {{ .Values.host | quote }}
