apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: {{ .Values.namespaces.issuer }}
  labels:
    {{- include "helm-cve-certificate.labels" . | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: {{ include "helm-cve-certificate.acmeUrl" . | quote }}
    # Email address used for ACME registration
    email: {{ .Values.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-dns-key
    solvers:
      - dns01:
          route53:
            region: {{ .Values.dns.region | quote }}
            hostedZoneID: {{ .Values.dns.hostedZoneID | quote }}
